version: '3.8'

#APP & DB are two different containers
#They are automatically connected to each other by docker on the docker network
#app container doesn't need a port to communicate here

services:
  #service for fastAPI
  app:
    build: .
    ports: 
      - "8000:80" #map 8000 computer port to 80 container port
    environment:
      #allows this container to access weathy database in the "db" container
      - DATABASE_URL=mongodb://db:27017/weathyDB
    depends_on:
      - db 


  db:
    image: mongo:latest 
    # ports:
    #   - somehting somehting
    volumes:
      #mongo-data = ssd thingy created
      #/data/db is physical organization - don't worry about it
     - mongo-data:/data/db

#mongo-data is a "storage space", like an ssd. NOT controlled by any container.
volumes: 
  mongo-data: 
